### ISSUE TITLE
Error translating "una"

### ISSUE THREAD

**Issue by Elisardojm** [apertium/apertium-es-gl#10]
I have tryed to translate "Voy para casa y llevo una caja" and the result was correct: "Vou para casa e levo unha caixa"

Then, I tryed to translate "Sujeta una caja", and the result was "Suxeita una caixa", that's incorrect, at this phrase "una" should be translated to "unha" too...

Could sombody fix it?

Thanks!

**Comment by ftyers** [comment]
Fixed in [33cca5e](https://github.com/apertium/apertium-spa/commit/33cca5ed9e15b8d237c0e49f8ff4451e1a4841ee#diff-49fa0025aa698e97ba023676e139960f).

$ echo "Sujeta una caja" | apertium -d . es-gl
Suxeita unha caixa

**Comment by TinoDidriksen** [comment]
Published to apertium.org.
